export const GET_HOLDING_REQUEST = "GET_HOLDING_REQUEST";
export const GET_HOLDING_SUCCESS = "GET_HOLDING_SUCCESS ";
export const GET_HOLDING_FAIL = "GET_HOLDING_FAIL";
export const GET_COIN_MARKET_REQUEST = "GET_COIN_MARKET_REQUEST";
export const GET_COIN_MARKET_SUCCESS = "GET_COIN_MARKET_SUCCESS";
export const GET_COIN_MARKET_FAIL = "GET_COIN_MARKET_FAIL";